1112007_1112059/1112007_1112059/Controllers/DonHangController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using _1112007_1112059.Filters;
using _1112007_1112059.Models;
using QuanLyDienThoaiBLL;
using WebMatrix.WebData;

namespace _1112007_1112059.Controllers
{
    [InitializeSimpleMembership]
    public class DonHangController : Controller
    {
        private QuanLyDienThoaiEntities db = new QuanLyDienThoaiEntities();

        public static int PageSize = 5;


        [Authorize(Roles = "Admin")]
        public ActionResult ThongKeDoanhSo()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        public PartialViewResult ThucHienThongKeDoanhSo(int? ngay, int? thang, int? nam, int? quy, string lua_chon)
        {
            decimal kq = 0;  
            if (lua_chon == "nam" && nam != null)  
                kq = db.DonHang.Sum(x => x.ngay_dat_hang.Value.Year == nam.Value ? x.tong_tien : 0).Value;  

            if (lua_chon == "quy" && nam != null && quy != null)  
            {
                for (int i = 3 * (quy.Value - 1) + 1; i <= 3 * quy.Value; ++i )  
                {
                    kq += db.DonHang.Sum(x => x.ngay_dat_hang.Value.Year == nam.Value &&
                        x.ngay_dat_hang.Value.Month == i  
                            ? x.tong_tien : 0).Value;  
                }
            }

            if (lua_chon == "thang" && thang != null && nam != null)
                kq = db.DonHang.Sum(x => x.ngay_dat_hang.Value.Year == nam.Value &&
                    x.ngay_dat_hang.Value.Month == thang.Value
                    ? x.tong_tien : 0).Value;  

            if (lua_chon == "ngay" && ngay != null && thang != null && nam != null)
            {
                kq = db.DonHang.Sum(x => x.ngay_dat_hang.Value.Year == nam.Value &&
                    x.ngay_dat_hang.Value.Month == thang.Value &&
                    x.ngay_dat_hang.Value.Day == ngay.Value   
                    ? x.tong_tien : 0).Value;   
            }

            ViewBag.kqDoanhThu = kq;   
            return PartialView("_ThucHienThongKeDoanhSo");   
        }

        [Authorize]
        public ActionResult XemChiTietLichSu(int ma_don_hang)
        {
            var ds_ChiTiet = db.ChiTietDonHang.Where(x => x.ma_don_hang == ma_don_hang);

            return View("_XemChiTietLichSu", ds_ChiTiet.ToList());
        }

        [Authorize]
        public ActionResult XemLichSuMuaHang(int page = 1)
        {
            var dsDonHang = db.DonHang.Where(x => x.nguoi_dat == WebSecurity.CurrentUserId);

            LishSuMuaHangViewModel model = new LishSuMuaHangViewModel
            {
                ds_donHang = dsDonHang.OrderByDescending(x => x.ngay_dat_hang).Skip((page - 1) * PageSize).Take(PageSize),
                pagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = dsDonHang.Count()
                }
            };

            return View(model);
        }
        [Authorize(Roles = "Admin")]
        public ActionResult CapNhatTrangThai(int ma_don_hang, int trang_thai_cap_nhat)
        {
            DonHang dh = db.DonHang.Where(x => x.id == ma_don_hang).FirstOrDefault();
            dh.trang_thai = trang_thai_cap_nhat;
            db.Entry(dh).State = EntityState.Modified;
            db.SaveChanges();


            return RedirectToAction("Index");
//            return PartialView("Index", db.DonHang.ToList());
        }

        //
        // GET: /DonHang/

        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            string[] ds_TrangThai = (from tt in db.TrangThaiDonHang
                                    select tt.trang_thai).ToArray();
            int[] ds_TrangThaiId = (from tt in db.TrangThaiDonHang
                                    select tt.id).ToArray();
            ViewData["ds_TrangThai"] = ds_TrangThai;
            ViewData["ds_TrangThaiId"] = ds_TrangThaiId;

            var donhang = db.DonHang.Include(d => d.ThongTinNguoiDung);
            return View(donhang.ToList());
        }

        //
        // GET: /DonHang/Details/5

        [Authorize(Roles = "Admin")]
        public ActionResult Details(int id = 0)
        {
            DonHang donhang = db.DonHang.Find(id);
            if (donhang == null)
            {
                return HttpNotFound();
            }
            return View(donhang);
        }

        //
        // GET: /DonHang/Create

        public ActionResult Create()
        {
            ViewBag.nguoi_dat = new SelectList(db.ThongTinNguoiDung, "UserId", "email");
            return View();
        }


        //
        // POST: /DonHang/Create

        [Authorize(Roles="User")]
        [HttpPost]
        public ActionResult Create(DonHang donhang)
        {
            GioHang gioHang = (GioHang)Session["GioHang"];
            DonHang dh = null;

            donhang.ngay_dat_hang = DateTime.Now;
            donhang.tong_tien = gioHang.TinhTongTien();
            donhang.nguoi_dat = WebSecurity.CurrentUserId;
            donhang.trang_thai = 0;
            if (ModelState.IsValid)
            {
                dh = db.DonHang.Add(donhang);
                db.SaveChanges();

                for (int i = 0; i < gioHang.ChiTietDonHang.Count(); ++i)
                {
                    ChiTietDonHang ct = new ChiTietDonHang
                    {
                        ma_gio_hang = null,
                        ma_don_hang = dh.id,
                        ma_dien_thoai = gioHang.ChiTietDonHang.ElementAt(i).ma_dien_thoai,
                        so_luong = gioHang.ChiTietDonHang.ElementAt(i).so_luong,
                        don_gia = gioHang.ChiTietDonHang.ElementAt(i).don_gia
                    };
                    db.ChiTietDonHang.Add(ct);
                    db.SaveChanges();
                }

                ViewBag.kq = 1;
                // Xoa gio hang sau khi da dat thanh cong
                gioHang.Clear();
            }

            ViewBag.kq = 0;
            return View("KetQuaDatHang", dh);
        }

        //
        // GET: /DonHang/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id = 0)
        {
            DonHang donhang = db.DonHang.Find(id);
            if (donhang == null)
            {
                return HttpNotFound();
            }
            ViewBag.nguoi_dat = new SelectList(db.ThongTinNguoiDung, "UserId", "email", donhang.nguoi_dat);
            return View(donhang);
        }

        //
        // POST: /DonHang/Edit/5
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Edit(DonHang donhang)
        {
            if (ModelState.IsValid)
            {
                db.Entry(donhang).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.nguoi_dat = new SelectList(db.ThongTinNguoiDung, "UserId", "email", donhang.nguoi_dat);
            return View(donhang);
        }

        //
        // GET: /DonHang/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id = 0)
        {
            DonHang donhang = db.DonHang.Find(id);
            if (donhang == null)
            {
                return HttpNotFound();
            }
            return View(donhang);
        }

        //
        // POST: /DonHang/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            DonHang donhang = db.DonHang.Find(id);
            db.DonHang.Remove(donhang);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

1112007_1112059/1112007_1112059/Views/DonHang/Create.cshtml
@model QuanLyDienThoaiBLL.DonHang

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>DonHang</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.ngay_dat_hang)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ngay_dat_hang)
            @Html.ValidationMessageFor(model => model.ngay_dat_hang)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.dia_chi_giao)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.dia_chi_giao)
            @Html.ValidationMessageFor(model => model.dia_chi_giao)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ten_nguoi_nhan)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ten_nguoi_nhan)
            @Html.ValidationMessageFor(model => model.ten_nguoi_nhan)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.dien_thoai)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.dien_thoai)
            @Html.ValidationMessageFor(model => model.dien_thoai)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.tong_tien)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.tong_tien)
            @Html.ValidationMessageFor(model => model.tong_tien)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.nguoi_dat, "ThongTinNguoiDung")
        </div>
        <div class="editor-field">
            @Html.DropDownList("nguoi_dat", String.Empty)
            @Html.ValidationMessageFor(model => model.nguoi_dat)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

1112007_1112059/1112007_1112059/Views/DonHang/Delete.cshtml
@model QuanLyDienThoaiBLL.DonHang

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>DonHang</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ngay_dat_hang)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ngay_dat_hang)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.dia_chi_giao)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.dia_chi_giao)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ten_nguoi_nhan)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ten_nguoi_nhan)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.dien_thoai)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.dien_thoai)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.tong_tien)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.tong_tien)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ThongTinNguoiDung.email)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ThongTinNguoiDung.email)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

1112007_1112059/1112007_1112059/Views/DonHang/Details.cshtml
@model QuanLyDienThoaiBLL.DonHang

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>DonHang</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ngay_dat_hang)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ngay_dat_hang)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.dia_chi_giao)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.dia_chi_giao)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ten_nguoi_nhan)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ten_nguoi_nhan)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.dien_thoai)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.dien_thoai)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.tong_tien)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.tong_tien)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ThongTinNguoiDung.email)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ThongTinNguoiDung.email)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

1112007_1112059/1112007_1112059/Views/DonHang/Edit.cshtml
@model QuanLyDienThoaiBLL.DonHang

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>DonHang</legend>

        @Html.HiddenFor(model => model.id)

        <div class="editor-label">
            @Html.LabelFor(model => model.ngay_dat_hang)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ngay_dat_hang)
            @Html.ValidationMessageFor(model => model.ngay_dat_hang)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.dia_chi_giao)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.dia_chi_giao)
            @Html.ValidationMessageFor(model => model.dia_chi_giao)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ten_nguoi_nhan)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ten_nguoi_nhan)
            @Html.ValidationMessageFor(model => model.ten_nguoi_nhan)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.dien_thoai)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.dien_thoai)
            @Html.ValidationMessageFor(model => model.dien_thoai)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.tong_tien)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.tong_tien)
            @Html.ValidationMessageFor(model => model.tong_tien)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.nguoi_dat, "ThongTinNguoiDung")
        </div>
        <div class="editor-field">
            @Html.DropDownList("nguoi_dat", String.Empty)
            @Html.ValidationMessageFor(model => model.nguoi_dat)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

1112007_1112059/1112007_1112059/Views/DonHang/Index.cshtml
@model IEnumerable<QuanLyDienThoaiBLL.DonHang>

@{
    Layout = null;
}

<div class="row space30">
    <div class="col-md-12">
        <h2>Xem lịch sử mua hàng</h2>
        @{
            System.Globalization.NumberFormatInfo nfi = System.Globalization.CultureInfo.CreateSpecificCulture("vi-VN").NumberFormat;
            nfi.NumberDecimalDigits = 0;
        }

        @{
                
                List<SelectListItem> ds_TrangThai = new List<SelectListItem>();

                for (int i = 0; i < ((string[])ViewData["ds_TrangThai"]).Count(); ++i )
                {
                    ds_TrangThai.Add(new SelectListItem
                    {
                        Text = ((string[])ViewData["ds_TrangThai"]).ElementAt(i),
                        Value = ((int[])ViewData["ds_TrangThaiId"]).ElementAt(i).ToString(),
                        Selected = false
                    });
                    
                }
            }


        <table class="table-lich-su-mua-hang">
            <tr>
                <th>Ngày đặt hàng</th>
                <th>Địa chỉ giao hàng</th>
                <th>Tên người nhận</th>
                <th>Điện thoại</th>
                <th>Tổng tiền</th>
                <th>Trạng thái</th>
            </tr>

            
            

            @foreach (var line in Model)
            {
                <tr>
                    <td>@line.ngay_dat_hang</td>
                    <td>@line.dia_chi_giao</td>
                    <td>@line.ten_nguoi_nhan</td>
                    <td>@line.dien_thoai</td>
                    <td>@line.tong_tien.GetValueOrDefault().ToString("N", @nfi) VNĐ</td>
                    <td>@line.TrangThaiDonHang.trang_thai
                        
                    </td>
                    <td>
                        

                        @using (Ajax.BeginForm("CapNhatTrangThai", "DonHang", new AjaxOptions
                                {
                                    HttpMethod = "POST",
                                    InsertionMode = InsertionMode.Replace,
                                    UpdateTargetId = "noi-dung-chuc-nang"
                                })) {

                                    foreach (var tt in ds_TrangThai)
                                    {
                                        tt.Selected = false;
                                        if (tt.Value == @line.TrangThaiDonHang.id.ToString())
                                        {
                                            tt.Selected = true;
                                        }
                                    }
                            
                                //ds_TrangThai.Where(x => x.Value == line.trang_thai.GetValueOrDefault().ToString()).FirstOrDefault().Selected = true;
                                    
                                       @Html.DropDownList("trang_thai_cap_nhat", ds_TrangThai) 
                                        <input type="hidden" name="ma_don_hang" value="@line.id" />
                                    
                                <input class="actionButtons" type="submit"
                                value="Cập nhật" />
                                    
                                }
                    </td>
                </tr>
            }

        </table>
    </div>
</div>





@*       <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>*@

1112007_1112059/1112007_1112059/Views/DonHang/KetQuaDatHang.cshtml
@model QuanLyDienThoaiBLL.DonHang

@{
    ViewBag.Title = "Kết quả đặt hàng";
}

<div id="container" class="container">

    <img src="/images/banner.jpg" alt="Simplex Header" class="img-responsive" />



    <ul class="nav nav-justified">
        <li><a href="/Home/Index">TRANG CHỦ</a></li>
        <li><a href="/SanPham/XemDanhSachSanPham">SẢN PHẨM</a></li>
        <li><a href="/SanPham/Index">TÌM SẢN PHẨM</a></li>
        <li><a href="gioi_thieu.html">GIỚI THIỆU</a></li>
        <li><a href="lien_he.html">LIÊN HỆ</a></li>
        <li><a href="dang_nhap.html">TÀI KHOẢN</a></li>
    </ul>

    <div class="row space30">
        <!-- row 1 begins -->

        <div class="col-md-12">
            <h2>Thông tin đặt hàng</h2>
            <p>Đơn hàng sẽ được vận chuyển trong thời gian sớm nhất, tối đa là 3 ngày</p>
            <table>
                <tr>
                    <th>Ngày đặt hàng: </th>
                    <td>@Model.ngay_dat_hang</td>
                </tr>
                <tr>
                    <th>Địa chỉ giao: </th>
                    <td>@Model.dia_chi_giao</td>
                </tr>
                <tr>
                    <th>Tên người nhận: </th>
                    <td>@Model.ten_nguoi_nhan</td>
                </tr>
                <tr>
                    <th>Điện thoại liên lạc: </th>
                    <td>@Model.dien_thoai</td>
                </tr>
                <tr>
                    <th>Tổng số tiền: </th>
                    <td>@Model.tong_tien</td>
                </tr>
            </table>
            </div>
    </div>
    <!-- Site footer -->
    <div class="footer">
        <p>
            Copyright © 2014 1112007-1112059
        </p>
    </div>
</div>

1112007_1112059/1112007_1112059/Views/DonHang/ThongKeDoanhSo.cshtml
@{
    Layout = null;
    }

 <div class="row space30">
        <!-- row 1 begins -->

        <div class="col-md-6">
            <h2>Thống kê doanh thu</h2>

            @using(Ajax.BeginForm("ThucHienThongKeDoanhSo", new AjaxOptions {
                HttpMethod = "POST",
                InsertionMode = InsertionMode.Replace,
                UpdateTargetId = "kq-thong-ke"
            }))
            {
            <table>
               
                <tr>
                    <th>Ngày</th>
                    <td>@Html.TextBox("ngay", null, new {@class="form-control"})</td>
                </tr>
                <tr>
                    <th>Tháng</th>
                    <td>@Html.TextBox("thang", null, new {@class="form-control"})</td>
                </tr>
                <tr>
                    <th>Qúy</th>
                    <td>@Html.TextBox("quy", null, new {@class="form-control"})</td>
                </tr>
                <tr>
                    <th>Năm</th>
                    <td>@Html.TextBox("nam", null, new {@class="form-control"})</td>
                </tr>
                
                
            </table>
                
                <h3>Thống kê theo</h3>
            <div>
            <div>
                   <input type="radio" name="lua_chon" value="ngay" />Ngày  
                </div>
            <div>
                        <input type="radio" name="lua_chon" value="thang" />Tháng  
                </div>       
                   <div>
                        <input type="radio" name="lua_chon" value="quy" />Quý  
     </div><div>
                        <input type="radio" name="lua_chon" value="nam" checked />Năm  
</div>
            </div>
                <div style="margin-top:10px">
                <input type="submit" value="Thống kê" /></div>
            }
            
            </div>
     <div class="col-md-6">
        <div id="kq-thong-ke"></div>
    </div>
 </div>

1112007_1112059/1112007_1112059/Views/DonHang/XemLichSuMuaHang.cshtml
@model _1112007_1112059.Models.LishSuMuaHangViewModel

@{
    ViewBag.Title = "Xem lịch sử mua hàng";
}

<div id="container" class="container">

    <img src="/images/banner.jpg" alt="Simplex Header" class="img-responsive" />

    <ul class="nav nav-justified">
            <li><a href="/Home/Index">TRANG CHỦ</a></li>
            <li><a href="/SanPham/XemDanhSachSanPham">SẢN PHẨM</a></li>
            <li><a href="/SanPham/TimSanPham">TÌM SẢN PHẨM</a></li>
            <li><a href="#">GIỚI THIỆU</a></li>
            <li><a href="#">LIÊN HỆ</a></li>
            <li><a href="/Account/Login">TÀI KHOẢN</a></li>
        </ul>

    

    <div class="row space30">
        <div class="col-md-12">
            <h2>Xem lịch sử mua hàng</h2>

            <div id="chi-tiet-lich-su">

            </div>
        </div>
    </div>

    <div class="row space30">
        <!-- row 1 begins -->

        <div class="col-md-12">
            
            @{
                System.Globalization.NumberFormatInfo nfi = System.Globalization.CultureInfo.CreateSpecificCulture("vi-VN").NumberFormat;
                nfi.NumberDecimalDigits = 0;
            }
            

            <table class="table-lich-su-mua-hang">
                <tr>
                    <th>Ngày đặt hàng</th>
                    <th>Địa chỉ giao hàng</th>
                    <th>Tên người nhận</th>
                    <th>Điện thoại</th>
                    <th>Tổng tiền</th>
                    <th>Trạng thái</th>
                </tr>

                @foreach (var line in Model.ds_donHang)
                {
                    <tr>
                        <td>@line.ngay_dat_hang</td>
                        <td>@line.dia_chi_giao</td>
                        <td>@line.ten_nguoi_nhan</td>
                        <td>@line.dien_thoai</td>
                        <td>@line.tong_tien.GetValueOrDefault().ToString("N", @nfi) VNĐ</td>
                        <td>@line.TrangThaiDonHang.trang_thai</td>
                        <td>@Ajax.ActionLink("Xem chi tiết", "XemChiTietLichSu", new { ma_don_hang = line.id },
                            new AjaxOptions
                            {
                                HttpMethod = "POST",
                                InsertionMode = InsertionMode.Replace,
                                UpdateTargetId = "chi-tiet-lich-su"
                            })
                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>

    <div class="row space30">  
        <div class="pager">
            @Html.PageLinks(Model.pagingInfo, x => Url.Action("XemLichSuMuaHang", new {page = x}))
        </div>
    </div>

    <!-- Site footer -->
    <div class="footer">
        <p>
            Copyright © 2014 1112007-1112059
        </p>
    </div>
</div>
<script type="text/javascript">
	window.onload=function(){
	var tfrow = document.getElementById('tfhover').rows.length;
	var tbRow=[];
	for (var i=1;i<tfrow;i++) {
		tbRow[i]=document.getElementById('tfhover').rows[i];
		tbRow[i].onmouseover = function(){
		  this.style.backgroundColor = '#171515';
		};
		tbRow[i].onmouseout = function() {
		  this.style.backgroundColor = '#2f2f2f';
		};
	}
};
</script>

1112007_1112059/1112007_1112059/Views/DonHang/_ThucHienThongKeDoanhSo.cshtml
@{
    System.Globalization.NumberFormatInfo nfi = System.Globalization.CultureInfo.CreateSpecificCulture("vi-VN").NumberFormat;
    nfi.NumberDecimalDigits = 0;

    int doanhthu = (int)ViewBag.kqDoanhThu;
    
    }


            <h2>Doanh thu @doanhthu.ToString("N", @nfi) VNĐ</h2>
            
            

1112007_1112059/1112007_1112059/Views/DonHang/_XemChiTietLichSu.cshtml
@model IEnumerable<QuanLyDienThoaiBLL.ChiTietDonHang>
@{
    Layout = null;
}

@{
    System.Globalization.NumberFormatInfo nfi = System.Globalization.CultureInfo.CreateSpecificCulture("vi-VN").NumberFormat;
    nfi.NumberDecimalDigits = 0;
}

<h3>Chi tiết đơn đặt hàng</h3>
<table class="table-lich-su-mua-hang">
    <tr>
        <th>Điện thoại
        </th>
        <th>Số lượng
        </th>
        <th>Đơn giá
        </th>
        <th>Tổng tiền cho sản phẩm
        </th>
    </tr>

    @foreach (var line in Model)
    {
        <tr>
            <td>
                @line.DienThoai.ten_dien_thoai
            </td>
            <td>
                @line.so_luong
            </td>
            <td>
                @line.don_gia.GetValueOrDefault().ToString("N", @nfi) VNĐ
            </td>
            <td>
                @{
        decimal tong = Convert.ToDecimal((decimal)line.so_luong) * (decimal)line.don_gia;
                }
                @tong.ToString("N", @nfi) VNĐ
            </td>
        </tr>
    }

</table>