1112007_1112059/1112007_1112059/Controllers/LoaiSanPhamController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using _1112007_1112059.Filters;
using _1112007_1112059.Models;
using QuanLyDienThoaiBLL;

namespace _1112007_1112059.Controllers
{
    [InitializeSimpleMembership]
    public class LoaiSanPhamController : Controller
    {
        private QuanLyDienThoaiEntities db = new QuanLyDienThoaiEntities();



        //
        // GET: /LoaiSanPham/

        [Authorize(Roles = "Admin")]
        public PartialViewResult Index()
        {
            return PartialView("Index", db.LoaiDienThoai.ToList());
        }

        //
        // GET: /LoaiSanPham/Details/5
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int id = 0)
        {
            LoaiDienThoai loaidienthoai = db.LoaiDienThoai.Find(id);  
            if (loaidienthoai == null)
            {
                return HttpNotFound();   
            }
            return View(loaidienthoai);  
        }

        //
        // GET: /LoaiSanPham/Create
        [Authorize(Roles = "Admin")]
        public PartialViewResult Create()   
        {
            return PartialView("Create");    
        }

        [Authorize(Roles = "Admin")]
        public PartialViewResult KhongThanhCong(LoaiDienThoai loaidienthoai)
        {
            return PartialView("Create", loaidienthoai);   
        }

        //
        // POST: /LoaiSanPham/Create
        [Authorize(Roles = "Admin")]  
        [HttpPost]
        public ActionResult Create(LoaiDienThoai loaidienthoai)
        {
            if (ModelState.IsValid)
            {
                db.LoaiDienThoai.Add(loaidienthoai);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return RedirectToAction("KhongThanhCong", loaidienthoai);
        }

        //
        // GET: /LoaiSanPham/Edit/5
        [Authorize(Roles = "Admin")]
        public PartialViewResult Edit(int id = 0)
        {
            LoaiDienThoai loaidienthoai = db.LoaiDienThoai.Find(id);
            if (loaidienthoai == null)
            {
                return PartialView("Index");
            }
            return PartialView("Edit", loaidienthoai);
        }

        //
        // POST: /LoaiSanPham/Edit/5
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Edit(LoaiDienThoai loaidienthoai)
        {
            if (ModelState.IsValid)
            {
                //db.Entry(loaidienthoai).State = EntityState.Modified;
                
                db.Entry(loaidienthoai).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(loaidienthoai);
        }

        //
        // GET: /LoaiSanPham/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id = 0)
        {
            LoaiDienThoai loaidienthoai = db.LoaiDienThoai.Find(id);   
            if (loaidienthoai == null)   
            {
                return HttpNotFound();   
            }
            return View(loaidienthoai);   
        }

        //
        // POST: /LoaiSanPham/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult DeleteConfirmed(int id)   
        {
            LoaiDienThoai loaidienthoai = db.LoaiDienThoai.Find(id);  
            db.LoaiDienThoai.Remove(loaidienthoai);  
            db.SaveChanges();  
            return RedirectToAction("Index");  
        }  

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

1112007_1112059/1112007_1112059/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QuanLyDienThoaiBLL;
using _1112007_1112059.Models;
using _1112007_1112059.Filters;

namespace _1112007_1112059.Controllers
{
    [InitializeSimpleMembership]
    public class SanPhamController : Controller
    {
        private QuanLyDienThoaiEntities db = new QuanLyDienThoaiEntities();
        public static int PageSize = 12;

        [Authorize(Roles = "Admin")]
        public PartialViewResult ThongKeTop10LoaiSP(int ma_loai)   
        {   
            IEnumerable<ThongKeTop10SanPham> ds_thong_ke = (from ctdh in db.ChiTietDonHang   
                                                            join dt in db.DienThoai   
                                                            on ctdh.ma_dien_thoai equals dt.ma_dien_thoai   
                                                            join ldt in db.LoaiDienThoai   
                                                            on dt.loai_dien_thoai equals ldt.ma_loai   
                                                            where ldt.ma_loai == ma_loai   
                                                            group ctdh by ctdh.ma_dien_thoai into g   
                                                            select new ThongKeTop10SanPham   
                                                            {
                                                                TenDienThoai = g.FirstOrDefault().DienThoai.ten_dien_thoai,
                                                                SoLuong = g.Sum(x => x.so_luong).Value
                                                            }).OrderByDescending(x => x.SoLuong).Take(10);
            return PartialView("_ThongKeTop10SanPham", ds_thong_ke);
        }     

        [Authorize(Roles = "Admin")]
        public PartialViewResult ThongKeTop10SanPham()
        {
            IEnumerable<ThongKeTop10SanPham> ds_thong_ke = (from ctdh in db.ChiTietDonHang
                               join dt in db.DienThoai
                               on ctdh.ma_dien_thoai equals dt.ma_dien_thoai
                               group ctdh by ctdh.ma_dien_thoai into g
                               select new ThongKeTop10SanPham
                               {
                                   TenDienThoai = g.FirstOrDefault().DienThoai.ten_dien_thoai,
                                   SoLuong = g.Sum(x => x.so_luong).Value
                               }).OrderByDescending(x => x.SoLuong).Take(10);
            return PartialView("_ThongKeTop10SanPham", ds_thong_ke);
        }

        public ActionResult TimSanPham(string ten_san_pham, string hang_san_xuat, string he_dieu_hanh,
                                string gia_tien, string kich_thuoc_man_hinh, string savedKey, int page = 1)
        {
            string tmpKey = ten_san_pham + hang_san_xuat + he_dieu_hanh + gia_tien + kich_thuoc_man_hinh;


            if (savedKey != tmpKey)
            {
                page = 1;
                savedKey = tmpKey;
            }

            var dienthoai = from dt in db.DienThoai
                            select dt;

            if (!String.IsNullOrEmpty(ten_san_pham))
            {

                dienthoai = dienthoai.Where(dt => dt.ten_dien_thoai.ToUpper()
                    .Contains(ten_san_pham.ToUpper()));
            }
            else
            {
                ten_san_pham = "";
                if (!String.IsNullOrEmpty(hang_san_xuat))
                {

                    dienthoai = dienthoai.Where(dt => dt.hang_san_xuat.ToUpper()
                        .Contains(hang_san_xuat.ToUpper()));
                }
                if (!String.IsNullOrEmpty(he_dieu_hanh))
                {

                    dienthoai = dienthoai.Where(dt => dt.he_dieu_danh.ToUpper()
                        .Contains(he_dieu_hanh.ToUpper()));
                }
                if (!String.IsNullOrEmpty(gia_tien))
                {

                    if (int.Parse(gia_tien) < 10)
                    {
                        string gia_nhap = gia_tien + "000000";
                        int i_gia_nhap = int.Parse(gia_nhap);

                        dienthoai = dienthoai.Where(dt => dt.gia <= i_gia_nhap);
                    }
                    else
                    {
                        string gia_nhap = gia_tien + "000000";
                        int i_gia_nhap = int.Parse(gia_nhap);

                        dienthoai = dienthoai.Where(dt => dt.gia >= i_gia_nhap);
                    }
                }
                if (!String.IsNullOrEmpty(kich_thuoc_man_hinh))
                {

                    dienthoai = dienthoai.Where(dt => dt.man_hinh.ToUpper()
                        .Contains(kich_thuoc_man_hinh.ToUpper()));
                }
            }




            DanhSachSanPhamViewModel model = new DanhSachSanPhamViewModel
            {

                ds_DienThoai = dienthoai.OrderBy(x => x.ma_dien_thoai).Skip((page - 1) * PageSize).Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    Ten_san_pham = ten_san_pham,
                    Hang_san_xuat = hang_san_xuat,
                    He_dieu_hanh = he_dieu_hanh,
                    Gia_tien = gia_tien,
                    Kich_thuoc_man_hinh = kich_thuoc_man_hinh,
                    SavedKey = savedKey,

                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = dienthoai.Count()
                }
            };

            return View(model);

        }


        public ActionResult XemChiTietSanPham(int id = 0, int page = 1)
        {
            DienThoai dienthoai = db.DienThoai.Find(id);
            if (dienthoai == null)
            {
                return HttpNotFound();  
            }

            var ds_binh_luan = (from bl in db.BinhLuanSanPham  
                                where bl.ma_dien_thoai == id  
                                orderby bl.ngay_binh_luan descending  
                                select bl)  
                                .Skip((page - 1) * PageSize).Take(PageSize).ToList();  

            var dem_binh_luan = from bl in db.BinhLuanSanPham  
                                where bl.ma_dien_thoai == id  
                                orderby bl.ngay_binh_luan descending  
                                select bl;  
            var tong_so_binh_luan = dem_binh_luan.Count();  
            
            var ds_hinh_dt = from h in db.HinhDienThoai
                             where h.ma_dien_thoai == id
                             select h;
            var so_lan_xem = db.SoLanXemDienThoai.Find(id);  
            if (so_lan_xem == null)     
            {
                SoLanXemDienThoai tmp = new SoLanXemDienThoai
                {
                    ma_dien_thoai = dienthoai.ma_dien_thoai,  
                    so_lan_xem = 1
                };
                db.SoLanXemDienThoai.Add(tmp);  
                db.SaveChanges();

                so_lan_xem = db.SoLanXemDienThoai.Find(id);  
            }
            else
            {
                so_lan_xem.so_lan_xem++;
                db.Entry(so_lan_xem).State = EntityState.Modified;
                db.SaveChanges();
            }
            var ds_sp_lien_quan = (from sp in db.DienThoai
                                  where sp.hang_san_xuat == dienthoai.hang_san_xuat
                                  && sp.ten_dien_thoai != dienthoai.ten_dien_thoai
                                  select sp).Take(4);

            XemChiTietSanPhamViewModel model = new XemChiTietSanPhamViewModel
            {
                ds_BinhLuan = ds_binh_luan,  
                dienThoai = dienthoai,  
                soLanXem = so_lan_xem,  
                ds_hinh = ds_hinh_dt,  
                ds_dienThoaiLienQuan = ds_sp_lien_quan,  
                pagingInfo = new PagingInfo  
                {
                    ma_dien_thoai = id,  
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = tong_so_binh_luan   
                }
            };

            ViewBag.IsLoggedIn = false;
            if (User.Identity.IsAuthenticated)
            {
                ViewBag.IsLoggedIn = true;
                ViewBag.TenDangNhap = User.Identity.Name;
            }

            return View(model);
        }

        public ActionResult XemDanhSachSanPham(int page = 1)
        {
            var dienthoais = db.DienThoai.Include("LoaiDienThoai");
            IEnumerable<DienThoai> danh_sach;

            danh_sach = dienthoais.OrderBy(t => t.hang_san_xuat).Skip((page - 1) * PageSize).Take(PageSize).ToList();


            DanhSachSanPhamViewModel model = new DanhSachSanPhamViewModel
            {

                ds_DienThoai = danh_sach,
                PagingInfo = new PagingInfo
                {
                    SortOrder = "hang",

                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = dienthoais.Count()
                }
            };

            return View(model);
        }

        //
        // GET: /SanPham/

        [Authorize(Roles="Admin")]
        public ActionResult DanhSachSanPham(string sortOrder, int ma_loai, int page = 1)
        {
            var dienthoais = db.DienThoai.Include("LoaiDienThoai").Where(x => x.loai_dien_thoai == ma_loai);
            IEnumerable<DienThoai> kq_search = dienthoais;
            if (sortOrder == "ten") {
                kq_search = dienthoais.OrderBy(t => t.ten_dien_thoai).Skip((page - 1) * PageSize).Take(PageSize).ToList();
            }
            else if (sortOrder == "gia") {
                kq_search = dienthoais.OrderBy(t => t.gia).Skip((page - 1) * PageSize).Take(PageSize).ToList();
            }

1112007_1112059/1112007_1112059/Views/LoaiSanPham/Create.cshtml
@model QuanLyDienThoaiBLL.LoaiDienThoai

@{
    Layout = null;
}

<div class="col-md-5">
    <h2>Thêm loại sản phẩm</h2>


    @using (Ajax.BeginForm("Create", new AjaxOptions
    {
                        HttpMethod = "POST",
                        InsertionMode = InsertionMode.Replace,
                        UpdateTargetId = "noi-dung-chuc-nang"   
                    }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Loại điện thoại</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.ma_loai)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.ma_loai, new { @class="form-control" })
            @Html.ValidationMessageFor(model => model.ma_loai)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ten_loai)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.ten_loai, new { @class="form-control" })
            @Html.ValidationMessageFor(model => model.ten_loai)
        </div>
        <br />
        <p>
            <input type="submit" class="btn-reset-password" value="Tạo loại sản phẩm" />
        </p>
    </fieldset>
    }
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

1112007_1112059/1112007_1112059/Views/LoaiSanPham/Delete.cshtml
@model QuanLyDienThoaiBLL.LoaiDienThoai

@{
    ViewBag.Title = "Xóa loại điện thoại";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="container" class="container">

    <img src="/images/banner.jpg" alt="Simplex Header" class="img-responsive" />



    <ul class="nav nav-justified">
        <li><a href="/Home/Index">TRANG CHỦ</a></li>
        <li class="active"><a href="/SanPham/DanhSachSanPham">SẢN PHẨM</a></li>
        <li><a href="/SanPham/Index">TÌM SẢN PHẨM</a></li>
        <li><a href="gioi_thieu.html">GIỚI THIỆU</a></li>
        <li><a href="lien_he.html">LIÊN HỆ</a></li>
        <li><a href="dang_nhap.html">TÀI KHOẢN</a></li>
    </ul>

    <div class="row space30">
        <!-- row 1 begins -->

        <div class="col-md-12">

            <h2>Xóa loại điện thoại</h2>

            <h3>Bạn có chắc muốn xóa loại sản phẩm này?</h3>
            <div class="table-ds-sp">
                <table>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.ma_loai)</th>
                        <td>@Html.DisplayFor(model => model.ma_loai)</td>
                    </tr>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.ten_loai)</th>
                        <td>@Html.DisplayFor(model => model.ten_loai)</td>
                    </tr>
                </table>
            </div>

            @using (Html.BeginForm())
            {
                <p>
                    <input type="submit" value="Xóa" />
                    <br/><br/>
        @Html.ActionLink("Quay về", "Index")
                </p>
            }
        </div>
    </div>
    <!-- Site footer -->
    <div class="footer">
        <p>
            Copyright © 2014 1112007-1112059
        </p>
    </div>
</div>

1112007_1112059/1112007_1112059/Views/LoaiSanPham/Details.cshtml
@model QuanLyDienThoaiBLL.LoaiDienThoai

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>LoaiDienThoai</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ma_loai)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ma_loai)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ten_loai)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ten_loai)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id=Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

1112007_1112059/1112007_1112059/Views/LoaiSanPham/Edit.cshtml
@model QuanLyDienThoaiBLL.LoaiDienThoai

@{
    Layout = null;
}
<div class="col-md-5">
    <h2>Chỉnh sửa loại sản phẩm</h2>

    @using (Ajax.BeginForm("Edit", new AjaxOptions
    {
        HttpMethod = "POST",
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "noi-dung-chuc-nang"
    }))
    {
        @Html.ValidationSummary(true)

        <fieldset>
            <legend>Loại điện thoại</legend>

            <div class="editor-label">
                @Html.LabelFor(model => model.ma_loai)
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(model => model.ma_loai, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ma_loai)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.ten_loai)
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(model => model.ten_loai, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ten_loai)
            </div>
            <br />
            <p>
                <input type="submit" value="Lưu chỉnh sửa" />
            </p>
        </fieldset>
    }
    
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

1112007_1112059/1112007_1112059/Views/LoaiSanPham/Index.cshtml
@model IEnumerable<QuanLyDienThoaiBLL.LoaiDienThoai>



<h2>Loại điện thoại</h2>

<p>
    @Ajax.ActionLink("Thêm mới loại điện thoại", "Create", "LoaiSanPham", null,
                new AjaxOptions
                {
                    HttpMethod = "GET",
                    InsertionMode = InsertionMode.Replace,
                    UpdateTargetId = "noi-dung-chuc-nang"   
                }, null)
</p>
    <table class="table-lich-su-mua-hang">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ma_loai)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ten_loai)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ma_loai)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ten_loai)
                </td>
                <td>
                    @Ajax.ActionLink("Edit", "Edit", "LoaiSanPham", new { id = item.ma_loai },
                    new AjaxOptions
                    {
                        HttpMethod = "GET",
                        InsertionMode = InsertionMode.Replace,
                        UpdateTargetId = "noi-dung-chuc-nang"   
                    }, null) | 
                    @Ajax.ActionLink("Delete", "DeleteConfirmed", "LoaiSanPham", new { id = item.ma_loai },
                    new AjaxOptions
                    {
                        HttpMethod = "POST",
                        InsertionMode = InsertionMode.Replace,
                        UpdateTargetId = "noi-dung-chuc-nang"   
                    }, null) | 
                    @Ajax.ActionLink("Quản lý danh sách điện thoại", "DanhSachSanPham", "SanPham", new { ma_loai = item.ma_loai },
                    new AjaxOptions
                    {
                        HttpMethod = "POST",
                        InsertionMode = InsertionMode.Replace,
                        UpdateTargetId = "danh-sach-dien-thoai"   
                    }, null) | 
                    @Ajax.ActionLink("Thống kê số lượng bán top 10 của loại", "ThongKeTop10LoaiSP", "SanPham", new { ma_loai = item.ma_loai },
                    new AjaxOptions
                    {
                        HttpMethod = "POST",
                        InsertionMode = InsertionMode.Replace,
                        UpdateTargetId = "danh-sach-dien-thoai"   
                    }, null)
                </td>
            </tr>
        }

    </table>

<div id="danh-sach-dien-thoai">

</div>
    