1112007_1112059/1112007_1112059/Models/DanhSachSanPhamViewModel.cs
using System.Collections.Generic;
using QuanLyDienThoaiBLL;

namespace _1112007_1112059.Models
{
    public class DanhSachSanPhamViewModel
    {
        public IEnumerable<DienThoai> ds_DienThoai { get; set; }
        public PagingInfo PagingInfo { get; set; }
    }
}    

1112007_1112059/1112007_1112059/Models/ThongKeTop10SanPham.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace _1112007_1112059.Models
{
    public class ThongKeTop10SanPham
    {
        [Display(Name = "Tên điện thoại")]  
        public string TenDienThoai { get; set; }  
          
        [Display(Name = "Số lượng")]  
        public int SoLuong { get; set; }  
    }
}

1112007_1112059/1112007_1112059/Models/XemChiTietSanPhamViewModel.cs
using System.Collections.Generic;
using QuanLyDienThoaiBLL;
namespace _1112007_1112059.Models
{
    public class XemChiTietSanPhamViewModel
    {
        public IEnumerable<BinhLuanSanPham> ds_BinhLuan { get; set; } 
        public DienThoai dienThoai { get; set; } 
        public IEnumerable<DienThoai> ds_dienThoaiLienQuan { get; set; } 
        public SoLanXemDienThoai soLanXem { get; set; } 
        public IEnumerable<HinhDienThoai> ds_hinh { get; set; } 
        public PagingInfo pagingInfo { get; set; } 
    }
}

1112007_1112059/1112007_1112059/Controllers/GioHangController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using _1112007_1112059.Filters;
using _1112007_1112059.Models;
using QuanLyDienThoaiBLL;

namespace _1112007_1112059.Controllers
{
    [InitializeSimpleMembership]
    public class GioHangController : Controller
    {
        private QuanLyDienThoaiEntities db = new QuanLyDienThoaiEntities();

        //private GioHang LayGioHang()
        //{
        //    GioHang gio_hang = (GioHang)Session["GioHang"];
        //    if (gio_hang == null)
        //    {
        //        gio_hang = new GioHang();
        //        gio_hang.id = 1;
        //        Session["GioHang"] = gio_hang;
        //    }
        //    return gio_hang;
        //}

        public PartialViewResult CapNhatSanPham(GioHang gioHang, int so_luong_cap_nhat, 
            int ma_dien_thoai, string returnUrl)
        {
            if (so_luong_cap_nhat >= 1)
            {
                gioHang.ChiTietDonHang.Where(x => x.ma_dien_thoai == ma_dien_thoai)
                    .FirstOrDefault().so_luong = so_luong_cap_nhat;
            }

            GioHangIndexViewModel model = new GioHangIndexViewModel
            {
                gio_hang = gioHang,
                ReturnUrl = returnUrl
            };

            return PartialView("_SanPhamPartial", model);
        }

        [Authorize(Roles = "User")]
        public ActionResult ThanhToan(GioHang gioHang, string returnUrl)
        {
            if (gioHang.ChiTietDonHang.Count() >= 1)
                return View(new DonHang());
            return Redirect(returnUrl);
        }

        public PartialViewResult TomTatGioHang(GioHang gioHang)
        {
            return PartialView(gioHang);
        }

        public RedirectToRouteResult ThemSanPham(GioHang gioHang, int ma_dien_thoai, string returnUrl)
        {
            DienThoai dt = db.DienThoai.FirstOrDefault(p => p.ma_dien_thoai == ma_dien_thoai);
            if (dt != null)
            {
                gioHang.ThemSanPham(dt, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }


        public PartialViewResult XoaSanPham(GioHang gioHang, int ma_dien_thoai, string returnUrl)
        {
            DienThoai dt = db.DienThoai.FirstOrDefault(p => p.ma_dien_thoai == ma_dien_thoai);

            if (dt != null)
            {
                gioHang.XoaSanPham(dt);
            }

            GioHangIndexViewModel model = new GioHangIndexViewModel
            {
                gio_hang = gioHang,
                ReturnUrl = returnUrl
            };

            //return RedirectToAction("Index", new { returnUrl });
            return PartialView("_SanPhamPartial", model);
        }

        //
        // GET: /GioHang/

        public ActionResult Index(GioHang gioHang, string returnUrl)
        {
            return View(new GioHangIndexViewModel
            {
                gio_hang = gioHang,
                ReturnUrl = returnUrl
            });
        }

        ////
        //// GET: /GioHang/Details/5

        //public ActionResult Details(int id = 0)
        //{
        //    GioHang giohang = db.GioHang.Find(id);
        //    if (giohang == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(giohang);
        //}

        ////
        //// GET: /GioHang/Create

        //public ActionResult Create()
        //{
        //    return View();
        //}

        ////
        //// POST: /GioHang/Create

        //[HttpPost]
        //public ActionResult Create(GioHang giohang)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.GioHang.Add(giohang);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(giohang);
        //}

        ////
        //// GET: /GioHang/Edit/5

        //public ActionResult Edit(int id = 0)
        //{
        //    GioHang giohang = db.GioHang.Find(id);
        //    if (giohang == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(giohang);
        //}

        ////
        //// POST: /GioHang/Edit/5

        //[HttpPost]
        //public ActionResult Edit(GioHang giohang)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(giohang).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View(giohang);
        //}

        ////
        //// GET: /GioHang/Delete/5

        //public ActionResult Delete(int id = 0)
        //{
        //    GioHang giohang = db.GioHang.Find(id);
        //    if (giohang == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(giohang);
        //}

        ////
        //// POST: /GioHang/Delete/5

        //[HttpPost, ActionName("Delete")]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    GioHang giohang = db.GioHang.Find(id);
        //    db.GioHang.Remove(giohang);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

1112007_1112059/1112007_1112059/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QuanLyDienThoaiBLL;
using _1112007_1112059.Models;
using _1112007_1112059.Filters;

namespace _1112007_1112059.Controllers
{
    [InitializeSimpleMembership]
    public class SanPhamController : Controller
    {
        private QuanLyDienThoaiEntities db = new QuanLyDienThoaiEntities();
        public static int PageSize = 12;

        [Authorize(Roles = "Admin")]
        public PartialViewResult ThongKeTop10LoaiSP(int ma_loai)   
        {   
            IEnumerable<ThongKeTop10SanPham> ds_thong_ke = (from ctdh in db.ChiTietDonHang   
                                                            join dt in db.DienThoai   
                                                            on ctdh.ma_dien_thoai equals dt.ma_dien_thoai   
                                                            join ldt in db.LoaiDienThoai   
                                                            on dt.loai_dien_thoai equals ldt.ma_loai   
                                                            where ldt.ma_loai == ma_loai   
                                                            group ctdh by ctdh.ma_dien_thoai into g   
                                                            select new ThongKeTop10SanPham   
                                                            {
                                                                TenDienThoai = g.FirstOrDefault().DienThoai.ten_dien_thoai,
                                                                SoLuong = g.Sum(x => x.so_luong).Value
                                                            }).OrderByDescending(x => x.SoLuong).Take(10);
            return PartialView("_ThongKeTop10SanPham", ds_thong_ke);
        }     

        [Authorize(Roles = "Admin")]
        public PartialViewResult ThongKeTop10SanPham()
        {
            IEnumerable<ThongKeTop10SanPham> ds_thong_ke = (from ctdh in db.ChiTietDonHang
                               join dt in db.DienThoai
                               on ctdh.ma_dien_thoai equals dt.ma_dien_thoai
                               group ctdh by ctdh.ma_dien_thoai into g
                               select new ThongKeTop10SanPham
                               {
                                   TenDienThoai = g.FirstOrDefault().DienThoai.ten_dien_thoai,
                                   SoLuong = g.Sum(x => x.so_luong).Value
                               }).OrderByDescending(x => x.SoLuong).Take(10);
            return PartialView("_ThongKeTop10SanPham", ds_thong_ke);
        }

        public ActionResult TimSanPham(string ten_san_pham, string hang_san_xuat, string he_dieu_hanh,
                                string gia_tien, string kich_thuoc_man_hinh, string savedKey, int page = 1)
        {
            string tmpKey = ten_san_pham + hang_san_xuat + he_dieu_hanh + gia_tien + kich_thuoc_man_hinh;


            if (savedKey != tmpKey)
            {
                page = 1;
                savedKey = tmpKey;
            }

            var dienthoai = from dt in db.DienThoai
                            select dt;

            if (!String.IsNullOrEmpty(ten_san_pham))
            {

                dienthoai = dienthoai.Where(dt => dt.ten_dien_thoai.ToUpper()
                    .Contains(ten_san_pham.ToUpper()));
            }
            else
            {
                ten_san_pham = "";
                if (!String.IsNullOrEmpty(hang_san_xuat))
                {

                    dienthoai = dienthoai.Where(dt => dt.hang_san_xuat.ToUpper()
                        .Contains(hang_san_xuat.ToUpper()));
                }
                if (!String.IsNullOrEmpty(he_dieu_hanh))
                {

                    dienthoai = dienthoai.Where(dt => dt.he_dieu_danh.ToUpper()
                        .Contains(he_dieu_hanh.ToUpper()));
                }
                if (!String.IsNullOrEmpty(gia_tien))
                {

                    if (int.Parse(gia_tien) < 10)
                    {
                        string gia_nhap = gia_tien + "000000";
                        int i_gia_nhap = int.Parse(gia_nhap);

                        dienthoai = dienthoai.Where(dt => dt.gia <= i_gia_nhap);
                    }
                    else
                    {
                        string gia_nhap = gia_tien + "000000";
                        int i_gia_nhap = int.Parse(gia_nhap);

                        dienthoai = dienthoai.Where(dt => dt.gia >= i_gia_nhap);
                    }
                }
                if (!String.IsNullOrEmpty(kich_thuoc_man_hinh))
                {

                    dienthoai = dienthoai.Where(dt => dt.man_hinh.ToUpper()
                        .Contains(kich_thuoc_man_hinh.ToUpper()));
                }
            }




            DanhSachSanPhamViewModel model = new DanhSachSanPhamViewModel
            {

                ds_DienThoai = dienthoai.OrderBy(x => x.ma_dien_thoai).Skip((page - 1) * PageSize).Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    Ten_san_pham = ten_san_pham,
                    Hang_san_xuat = hang_san_xuat,
                    He_dieu_hanh = he_dieu_hanh,
                    Gia_tien = gia_tien,
                    Kich_thuoc_man_hinh = kich_thuoc_man_hinh,
                    SavedKey = savedKey,

                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = dienthoai.Count()
                }
            };

            return View(model);

        }


        public ActionResult XemChiTietSanPham(int id = 0, int page = 1)
        {
            DienThoai dienthoai = db.DienThoai.Find(id);
            if (dienthoai == null)
            {
                return HttpNotFound();  
            }

            var ds_binh_luan = (from bl in db.BinhLuanSanPham  
                                where bl.ma_dien_thoai == id  
                                orderby bl.ngay_binh_luan descending  
                                select bl)  
                                .Skip((page - 1) * PageSize).Take(PageSize).ToList();  

            var dem_binh_luan = from bl in db.BinhLuanSanPham  
                                where bl.ma_dien_thoai == id  
                                orderby bl.ngay_binh_luan descending  
                                select bl;  
            var tong_so_binh_luan = dem_binh_luan.Count();  
            
            var ds_hinh_dt = from h in db.HinhDienThoai
                             where h.ma_dien_thoai == id
                             select h;
            var so_lan_xem = db.SoLanXemDienThoai.Find(id);  
            if (so_lan_xem == null)     
            {
                SoLanXemDienThoai tmp = new SoLanXemDienThoai
                {
                    ma_dien_thoai = dienthoai.ma_dien_thoai,  
                    so_lan_xem = 1
                };
                db.SoLanXemDienThoai.Add(tmp);  
                db.SaveChanges();

                so_lan_xem = db.SoLanXemDienThoai.Find(id);  
            }
            else
            {
                so_lan_xem.so_lan_xem++;
                db.Entry(so_lan_xem).State = EntityState.Modified;
                db.SaveChanges();
            }
            var ds_sp_lien_quan = (from sp in db.DienThoai
                                  where sp.hang_san_xuat == dienthoai.hang_san_xuat
                                  && sp.ten_dien_thoai != dienthoai.ten_dien_thoai
                                  select sp).Take(4);

            XemChiTietSanPhamViewModel model = new XemChiTietSanPhamViewModel
            {
                ds_BinhLuan = ds_binh_luan,  
                dienThoai = dienthoai,  
                soLanXem = so_lan_xem,  
                ds_hinh = ds_hinh_dt,  
                ds_dienThoaiLienQuan = ds_sp_lien_quan,  
                pagingInfo = new PagingInfo  
                {
                    ma_dien_thoai = id,  
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = tong_so_binh_luan   
                }
            };

            ViewBag.IsLoggedIn = false;
            if (User.Identity.IsAuthenticated)
            {
                ViewBag.IsLoggedIn = true;
                ViewBag.TenDangNhap = User.Identity.Name;
            }

            return View(model);
        }

        public ActionResult XemDanhSachSanPham(int page = 1)
        {
            var dienthoais = db.DienThoai.Include("LoaiDienThoai");
            IEnumerable<DienThoai> danh_sach;

            danh_sach = dienthoais.OrderBy(t => t.hang_san_xuat).Skip((page - 1) * PageSize).Take(PageSize).ToList();


            DanhSachSanPhamViewModel model = new DanhSachSanPhamViewModel
            {

                ds_DienThoai = danh_sach,
                PagingInfo = new PagingInfo
                {
                    SortOrder = "hang",

                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = dienthoais.Count()
                }
            };

            return View(model);
        }

        //
        // GET: /SanPham/

        [Authorize(Roles="Admin")]
        public ActionResult DanhSachSanPham(string sortOrder, int ma_loai, int page = 1)
        {
            var dienthoais = db.DienThoai.Include("LoaiDienThoai").Where(x => x.loai_dien_thoai == ma_loai);
            IEnumerable<DienThoai> kq_search = dienthoais;
            if (sortOrder == "ten") {
                kq_search = dienthoais.OrderBy(t => t.ten_dien_thoai).Skip((page - 1) * PageSize).Take(PageSize).ToList();
            }
            else if (sortOrder == "gia") {
                kq_search = dienthoais.OrderBy(t => t.gia).Skip((page - 1) * PageSize).Take(PageSize).ToList();
            }

1112007_1112059/1112007_1112059/Views/SanPham/TimSanPham.cshtml
@model _1112007_1112059.Models.DanhSachSanPhamViewModel


@{
    ViewBag.Title = "Tìm sản phẩm";
}

<div id="container" class="container">

    <img src="/images/banner.jpg" alt="Simplex Header" class="img-responsive" />

    <ul class="nav nav-justified">
            <li><a href="/Home/Index">TRANG CHỦ</a></li>
            <li><a href="/SanPham/XemDanhSachSanPham">SẢN PHẨM</a></li>
            <li class="active"><a href="/SanPham/TimSanPham">TÌM SẢN PHẨM</a></li>
            <li><a href="#">GIỚI THIỆU</a></li>
            <li><a href="#">LIÊN HỆ</a></li>
            <li><a href="/Account/Login">TÀI KHOẢN</a></li>
        </ul>

    
    <div class="row space30">
        <!-- row 1 begins -->

        <div class="col-md-4">
            <h2>Tìm kiếm sản phẩm</h2>

            @{
                System.Globalization.NumberFormatInfo nfi = System.Globalization.CultureInfo.CreateSpecificCulture("vi-VN").NumberFormat;
                nfi.NumberDecimalDigits = 0;
            }

            @using (Html.BeginForm("TimSanPham", "SanPham", FormMethod.Get))
            {
                <div class="form-group">
                    <label for="ten_san_pham">
                        Tên sản phẩm:
                    </label>
                    @Html.TextBox("ten_san_pham",null, new { @class="form-control" })
                </div>
                <button type="submit" class="btn btn-default">Tìm kiếm</button>
            }
        </div>
        <div class="col-md-2"></div>
        <div class="col-md-4">
            <h2>Tìm kiếm nâng cao</h2>

            @using (Html.BeginForm("TimSanPham", "SanPham", FormMethod.Get))
            {
                
                <div class="form-group">
                    <label for="hang_san_xuat">
                        Hãng sản xuất:
                    </label>
                    @Html.DropDownList("hang_san_xuat", new[] {
                            new SelectListItem() {Text = "Samsung", Value = "Samsung"},
                            new SelectListItem() {Text = "Apple", Value = "Apple"},
                            new SelectListItem() {Text = "Nokia", Value = "Nokia"},
                            new SelectListItem() {Text = "HTC", Value = "HTC"}}, "Chọn hãng sản xuất", new { @class="form-control" })
                </div>
                <div class="form-group">
                    <label for="he_dieu_hanh">
                        Hệ điều hành:
                    </label>
                    @Html.DropDownList("he_dieu_hanh", new[] {
                            new SelectListItem() {Text = "Android", Value = "Android"},
                            new SelectListItem() {Text = "Window Phone", Value = "Window Phone"},
                            new SelectListItem() {Text = "IOS", Value = "IOS"}}, "Chọn hệ điều hành", new { @class="form-control" })
                </div>
                <div class="form-group">
                    <label for="gia_tien">
                        Giá tiền:</label>
                    @Html.DropDownList("gia_tien", new[] {
                            new SelectListItem() {Text = "Dưới 2 triệu", Value = "2"},
                            new SelectListItem() {Text = "Dưới 3 triệu", Value = "3"},
                            new SelectListItem() {Text = "Dưới 5 triệu", Value = "5"},
                            new SelectListItem() {Text = "Dưới 6 triệu", Value = "8"},
                            new SelectListItem() {Text = "Trên 10 triệu", Value = "10"}}, "Chọn giá tiền", new { @class="form-control" })
                </div>
                <div class="form-group">
                    <label for="kich_thuoc_man_hinh">
                        Kích thước màn hình:</label>
                    @Html.DropDownList("kich_thuoc_man_hinh", new[] {
                            new SelectListItem() {Text = "3.1inches Full HD", Value = "3.1inches Full HD"},
                            new SelectListItem() {Text = "4.5inches Full HD", Value = "4.5inches Full HD"},
                            new SelectListItem() {Text = "4.8inches Full HD", Value = "4.8inches Full HD"},
                            new SelectListItem() {Text = "5.0inches Full HD", Value = "5.0inches Full HD"},
                            new SelectListItem() {Text = "5.1inches Full HD", Value = "5.1inches Full HD"},
                            new SelectListItem() {Text = "5.3inches Full HD", Value = "5.3inches Full HD"}}, "Chọn kích thước màn hình", new { @class="form-control" })
                </div>
                <button type="submit" class="btn btn-default">Tìm kiếm</button>
            }
        </div>

    </div>
    <!-- /row 1 -->


    <div class="row space30">
        <!-- row 1 begins -->
            <h2>Danh sách sản phẩm</h2>
        </div>

            @for (int i = 0; i < Model.ds_DienThoai.Count(); i = i + 4)
            {
                @:<div class="row space30">
                string ten_dt = Model.ds_DienThoai.ElementAt(i).ten_dien_thoai;
                string duong_dan = "/Images/" + ten_dt + ".jpg";
                
                <div class="col-xs-6 col-sm-3">
                    <h3>@ten_dt</h3>
                    <a href="#">
                      <img src="@duong_dan" alt="@ten_dt" class="img-responsive img-rounded img_bottom" />
                    </a>
                    <p>
                            @ten_dt<br />
                            <span class="price">@Model.ds_DienThoai.ElementAt(i).gia.ToString("N", @nfi) VNĐ</span></p>
                    <p>
                        <a class="btn-sm btn-primary" href="/SanPham/XemChiTietSanPham/@Model.ds_DienThoai.ElementAt(i).ma_dien_thoai">Chi tiết &raquo;</a>
                        @using (Html.BeginForm("ThemSanPham", "GioHang"))
                        {
                            @Html.Hidden("ma_dien_thoai", Model.ds_DienThoai.ElementAt(i).ma_dien_thoai)
                            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                            <input class="them-vao-gio" type="submit" value="+ Thêm vào giỏ" />
                        }
                    </p>
                </div>
                
                if (i + 1 < Model.ds_DienThoai.Count())
                {
                    ten_dt = Model.ds_DienThoai.ElementAt(i + 1).ten_dien_thoai;
                    duong_dan = "/Images/" + ten_dt + ".jpg";
                
                    <div class="col-xs-6 col-sm-3">
                        <h3>@ten_dt</h3>
                        <a href="#">
                          <img src="@duong_dan" alt="@ten_dt" class="img-responsive img-rounded img_bottom" />
                        </a>
                        <p>
                                @ten_dt<br />
                                <span class="price">@Model.ds_DienThoai.ElementAt(i + 1).gia.ToString("N", @nfi) VNĐ</span></p>
                        <p>
                            <a class="btn-sm btn-success" href="/SanPham/XemChiTietSanPham/@Model.ds_DienThoai.ElementAt(i + 1).ma_dien_thoai">Chi tiết &raquo;</a>
                            @using (Html.BeginForm("ThemSanPham", "GioHang"))
                        {
                            @Html.Hidden("ma_dien_thoai", Model.ds_DienThoai.ElementAt(i + 1).ma_dien_thoai)
                            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                            <input class="them-vao-gio" type="submit" value="+ Thêm vào giỏ" />
                        }
                        </p>
                    </div>
                }
                
                
                if (i + 2 < Model.ds_DienThoai.Count())
                {
                    ten_dt = Model.ds_DienThoai.ElementAt(i + 2).ten_dien_thoai;
                    duong_dan = "/Images/" + ten_dt + ".jpg";
                    <div class="col-xs-6 col-sm-3">
                        <h3>@ten_dt</h3>
                        <a href="#">
                          <img src="@duong_dan" alt="@ten_dt" class="img-responsive img-rounded img_bottom" />
                        </a>
                        <p>
                                @ten_dt<br />
                                <span class="price">@Model.ds_DienThoai.ElementAt(i + 2).gia.ToString("N", @nfi) VNĐ</span></p>
                        <p>
                            <a class="btn-sm btn-primary" href="/SanPham/XemChiTietSanPham/@Model.ds_DienThoai.ElementAt(i + 2).ma_dien_thoai">Chi tiết &raquo;</a>
                            @using (Html.BeginForm("ThemSanPham", "GioHang"))
                        {
                            @Html.Hidden("ma_dien_thoai", Model.ds_DienThoai.ElementAt(i + 2).ma_dien_thoai)
                            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                            <input class="them-vao-gio" type="submit" value="+ Thêm vào giỏ" />
                        }
                        </p>
                    </div>
                }
                
                
                if (i + 3 < Model.ds_DienThoai.Count())
                {
                    ten_dt = Model.ds_DienThoai.ElementAt(i + 3).ten_dien_thoai;
                    duong_dan = "/Images/" + ten_dt + ".jpg";
                    <div class="col-xs-6 col-sm-3">
                        <h3>@ten_dt</h3>
                        <a href="#">
                          <img src="@duong_dan" alt="@ten_dt" class="img-responsive img-rounded img_bottom" />
                        </a>
                        <p>
                                @ten_dt<br />
                                <span class="price">@Model.ds_DienThoai.ElementAt(i + 3).gia.ToString("N", @nfi) VNĐ</span></p>
                        <p>
                            <a class="btn-sm btn-success" href="/SanPham/XemChiTietSanPham/@Model.ds_DienThoai.ElementAt(i + 3).ma_dien_thoai">Chi tiết &raquo;</a>
                            @using (Html.BeginForm("ThemSanPham", "GioHang"))
                        {
                            @Html.Hidden("ma_dien_thoai", Model.ds_DienThoai.ElementAt(i + 3).ma_dien_thoai)
                            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                            <input class="them-vao-gio" type="submit" value="+ Thêm vào giỏ" />
                        }
                        </p>
                    </div>
                }
                @:</div>
            }

            
                

    <div class="row space30">  
        <div class="pager">
            @Html.PageLinks(Model.PagingInfo, x => Url.Action("TimSanPham", new {page = x}))
        </div>
    </div>


    <!-- Site footer -->
    <div class="footer">
        <p>
            Copyright © 2014 1112007-1112059
        </p>
    </div>
</div>
<!-- /container -->
<!-- Bootstrap core JavaScript
    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->

1112007_1112059/1112007_1112059/Views/SanPham/_ThongKeTop10SanPham.cshtml
@model IEnumerable<_1112007_1112059.Models.ThongKeTop10SanPham>


<h2>Top 10 sản phẩm bán chạy</h2>
<table class="table-lich-su-mua-hang">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TenDienThoai)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SoLuong)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TenDienThoai)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SoLuong)
        </td>
    </tr>
}

</table>